name: noj-ml
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas=2.2.3
  - numpy>=1.24
  - scipy>=1.10
  - scikit-learn>=1.3
  - jupyter
  - matplotlib
  - seaborn
  - pip
  - pip:
    # Případné pip balíčky zde
    # - nějaký-balíček
variables:
  # Prostředí proměnné (volitelné)
  PYTHONPATH: $CONDA_PREFIX/lib/python3.10/site-packages
